include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-quark-lite
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for OpenList Quark Lite
LUCI_DEPENDS:=+openlist-quark-lite

include $(TOPDIR)/feeds/luci/luci.mk
