#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
	config_load quark-lite
	config_get_bool enabled main enabled 0
	config_get data_dir main data_dir /etc/openlist-quark-lite
	config_get delayed_start main delayed_start 10

	[ "$enabled" = "1" ] || return 0
	mkdir -p "$data_dir"

	procd_open_instance
	procd_set_param command /bin/sh -c "sleep $delayed_start; exec /usr/bin/openlist-quark-lite server --data '$data_dir'"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param limits nofile="65535 65535"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger quark-lite
}
